### PR TITLE
chore: Delete Postgres Media

### PR DESCRIPTION
**Pull request by tomthornton**
### About
Deletes postgres media when it is deleted in Rock

### Testing

`pytest -k "cover_image" -s`
### Screenshots
 
Screen Shot 2021-09-27 at 12 59 35 PM

### CODE REVIEW

**Comment by vinnyjth** [comment]
@tomthornton I'm struggling to evaluate this PR since it looks like it contains commits from several other PRs. Could you please catch this up to master and eliminate the commits from other PRs that aren't yet merged?

**Comment by vinnyjth** [comment]
How are you typically doing your branching when starting new work? Are you returning to `master` before you checkout a new branch?

**Comment by tomthornton** [comment]
@vinnyjth I'm creating a new branch from master each time. I'll see if I can rebase.

**Comment by vinnyjth** [comment]
Hey @tomthornton  - I'm still seeing code from the ContentItemConnection PR in this PR.

**Comment by tomthornton** [comment]
@vinnyjth removed the content item connection stuff

**Review by vinnyjth — APPROVED** [review]

**Pull request merged**
