### PR TITLE
chore: make tags run as backfill every time

### PR DESCRIPTION
**Pull request by nlewis84**
### About
This PR addresses a problem with the delta DAG properties that was causing rock tag DAG to not work.

Screen Shot 2021-11-17 at 8 39 58 AM

### Testing
@tomthornton I could use some help with testing this out.

### Screenshots

Screen Shot 2021-11-17 at 9 26 18 AM

### CODE REVIEW

**Review by tomthornton — APPROVED** [review]

**Comment by vinnyjth** [comment]
FWIW - I'm not certain that was actually the issue, it could be something else entirely. I would love to address the root cause :)

**Comment by nlewis84** [comment]
@tomthornton is in there right now checking another issue, so he can probably knock out two birds with one stone.

**Comment by vinnyjth** [comment]
@nlewis84 awesome!

**Comment by tomthornton** [comment]
@vinnyjth yeah I agree. How's this? https://github.com/ApollosProject/apollos-shovel/pull/99

**Pull request merged**
