### PR TITLE
feat: Add organization feature for VCC

### PR DESCRIPTION
**Pull request by tomthornton**
### About
Adds an organization feature

### Testing

Run `vineyard_backfill_rock_content_item_dag`

### Screenshot
Screen Shot 2021-11-10 at 12 49 46 PM

### CODE REVIEW

**Comment by nlewis84** [comment]
@tomthornton Trying to test this locally, and I get `buildkit not supported by daemon` error when i run `astro dev start`. Have you seen this before?

**Comment by nlewis84** [comment]
Nevermind...I forgot about `DOCKER_BUILDKIT=0 astro dev start`

**Comment by redreceipt** [comment]
@tomthornton this should be custom only for vineyard. Move it over there and I'll approve.

**Comment by tomthornton** [comment]
@redreceipt this can't really be vineyard only. I'd have to make an entire copy of `rock_features` just for vineyard.

**Comment by redreceipt** [comment]
These aren't core features, it needs to be custom. We'll have to figure out a way to make it happen. There shouldn't be unused code in the core libraries.

**Comment by nlewis84** [comment]
@tomthornton I ran the dag successfully, but am not seeing these features added to the feature table. I would expect an additional organization feature to show up here. Some other step that I am missing?

Screen Shot 2021-11-12 at 10 12 06 AM

**Comment by nlewis84** [comment]
Is it an option for us to push up this change, then remove the unused code from the core library sometime next week? Seems like that may be more work than we can finish today.

**Comment by redreceipt** [comment]
The better option would be to copy the whole rock-features file into VCC dags and then shrink it down later

**Comment by tomthornton** [comment]
I believe we could just extend the class and overwrite those one or two functions that need it.

**Comment by tomthornton** [comment]
@redreceipt okay I've added the custom code just for VCC. This should work.

**Review by redreceipt — APPROVED** [review]

**Pull request merged**
