### PR TITLE
fixes bug in updating features

### PR DESCRIPTION
**Pull request by redreceipt**

### CODE REVIEW

**Review by vinnyjth — APPROVED** [review]

**Comment by vinnyjth** [comment]
@redreceipt Can you fix the tests in this PR? I think they were actually broken by a former PR (the attribute keys one), not sure we are only seeing errors now.

**Comment by redreceipt** [comment]
Yep I’ll get them cleaned up.

**Comment by redreceipt** [comment]
fixed it, needed a `postgres` user since the remote DB we're pulling has it in its schema. Now learning about `vcr` and `casettes` to understand what is happening with this test failure.

**Comment by vinnyjth** [comment]
> fixed it, needed a `postgres` user since the remote DB we're pulling has it in its schema. Now learning about `vcr` and `casettes` to understand what is happening with this test failure.

This might be a case of needing to manually edit the VCR casettes :) The failure appears to be that we are making network requests that are unmocked. However, what has actually changed is the POST data for the network requests. We should be able to solve the issue by adding / editing the YML of the mocks of failing tests so the cassettes we have created are used again.

**Comment by redreceipt** [comment]
ok @vinnyjth take a look

**Review by vinnyjth — APPROVED** [review]

**Pull request merged**
