### PR TITLE
feat: Added persona tag dag

### PR DESCRIPTION
**Pull request by vinnyjth**

### CODE REVIEW

**Comment by vinnyjth** [comment]
Screen Shot 2021-07-07 at 3 37 17 PM

**Comment by vinnyjth** [comment]
Depends on https://github.com/ApollosProject/apollos-apps/pull/2051

**Comment by vinnyjth** [comment]
https://github.com/ApollosProject/apollos-apps/pull/2051 was merged!

**Review by tomthornton — APPROVED** [review]
Looks good!

**Pull request merged**
